// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: bookticker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookTicker struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	Channel          string                      `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Publicbookticker *PublicAggreBookTickerV3Api `protobuf:"bytes,315,opt,name=publicbookticker,proto3" json:"publicbookticker,omitempty"`
	Symbol           string                      `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Sendtime         uint64                      `protobuf:"varint,6,opt,name=sendtime,proto3" json:"sendtime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BookTicker) Reset() {
	*x = BookTicker{}
	mi := &file_bookticker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookTicker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTicker) ProtoMessage() {}

func (x *BookTicker) ProtoReflect() protoreflect.Message {
	mi := &file_bookticker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTicker.ProtoReflect.Descriptor instead.
func (*BookTicker) Descriptor() ([]byte, []int) {
	return file_bookticker_proto_rawDescGZIP(), []int{0}
}

func (x *BookTicker) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *BookTicker) GetPublicbookticker() *PublicAggreBookTickerV3Api {
	if x != nil {
		return x.Publicbookticker
	}
	return nil
}

func (x *BookTicker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BookTicker) GetSendtime() uint64 {
	if x != nil {
		return x.Sendtime
	}
	return 0
}

type PublicAggreBookTickerV3Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidPrice      string                 `protobuf:"bytes,1,opt,name=bidPrice,proto3" json:"bidPrice,omitempty"`
	BidQuantity   string                 `protobuf:"bytes,2,opt,name=bidQuantity,proto3" json:"bidQuantity,omitempty"`
	AskPrice      string                 `protobuf:"bytes,3,opt,name=askPrice,proto3" json:"askPrice,omitempty"`
	AskQuantity   string                 `protobuf:"bytes,4,opt,name=askQuantity,proto3" json:"askQuantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicAggreBookTickerV3Api) Reset() {
	*x = PublicAggreBookTickerV3Api{}
	mi := &file_bookticker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicAggreBookTickerV3Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAggreBookTickerV3Api) ProtoMessage() {}

func (x *PublicAggreBookTickerV3Api) ProtoReflect() protoreflect.Message {
	mi := &file_bookticker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAggreBookTickerV3Api.ProtoReflect.Descriptor instead.
func (*PublicAggreBookTickerV3Api) Descriptor() ([]byte, []int) {
	return file_bookticker_proto_rawDescGZIP(), []int{1}
}

func (x *PublicAggreBookTickerV3Api) GetBidPrice() string {
	if x != nil {
		return x.BidPrice
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetBidQuantity() string {
	if x != nil {
		return x.BidQuantity
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetAskPrice() string {
	if x != nil {
		return x.AskPrice
	}
	return ""
}

func (x *PublicAggreBookTickerV3Api) GetAskQuantity() string {
	if x != nil {
		return x.AskQuantity
	}
	return ""
}

var File_bookticker_proto protoreflect.FileDescriptor

const file_bookticker_proto_rawDesc = "" +
	"\n" +
	"\x10bookticker.proto\"\xa4\x01\n" +
	"\n" +
	"BookTicker\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12H\n" +
	"\x10publicbookticker\x18\xbb\x02 \x01(\v2\x1b.PublicAggreBookTickerV3ApiR\x10publicbookticker\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bsendtime\x18\x06 \x01(\x04R\bsendtime\"\x98\x01\n" +
	"\x1aPublicAggreBookTickerV3Api\x12\x1a\n" +
	"\bbidPrice\x18\x01 \x01(\tR\bbidPrice\x12 \n" +
	"\vbidQuantity\x18\x02 \x01(\tR\vbidQuantity\x12\x1a\n" +
	"\baskPrice\x18\x03 \x01(\tR\baskPrice\x12 \n" +
	"\vaskQuantity\x18\x04 \x01(\tR\vaskQuantityB\x06Z\x04./pbb\x06proto3"

var (
	file_bookticker_proto_rawDescOnce sync.Once
	file_bookticker_proto_rawDescData []byte
)

func file_bookticker_proto_rawDescGZIP() []byte {
	file_bookticker_proto_rawDescOnce.Do(func() {
		file_bookticker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookticker_proto_rawDesc), len(file_bookticker_proto_rawDesc)))
	})
	return file_bookticker_proto_rawDescData
}

var file_bookticker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bookticker_proto_goTypes = []any{
	(*BookTicker)(nil),                 // 0: BookTicker
	(*PublicAggreBookTickerV3Api)(nil), // 1: PublicAggreBookTickerV3Api
}
var file_bookticker_proto_depIdxs = []int32{
	1, // 0: BookTicker.publicbookticker:type_name -> PublicAggreBookTickerV3Api
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bookticker_proto_init() }
func file_bookticker_proto_init() {
	if File_bookticker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookticker_proto_rawDesc), len(file_bookticker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bookticker_proto_goTypes,
		DependencyIndexes: file_bookticker_proto_depIdxs,
		MessageInfos:      file_bookticker_proto_msgTypes,
	}.Build()
	File_bookticker_proto = out.File
	file_bookticker_proto_goTypes = nil
	file_bookticker_proto_depIdxs = nil
}
